# Generated by Django 4.2.2 on 2023-06-23 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helloworld',
            old_name='test',
            new_name='text',
        ),
    ]
